### PR TITLE
Allow filtering of resources

### PR DESCRIPTION
**Pull request by ryanmitchell**
Suggested change to allow filtering of resources in the API. I'm not overly familiar with Laravel so this may have implications.
e.g. /api/menus?location=1

If you are happy with this approach, there are some minor changes required to the ti-ext-local package too (e.g. pageSize becomes pageLimit). While on that topic, is there a reason why these API resources are in ext-local rather than ext-api, would it make sense to migrate them so the API extension is stand alone?

### CODE REVIEW

**Comment by sampoyigi** [comment]
Thank you, I'm happy with your approach with using the scope. The idea was to keep things separated as much as possible but you're right migrating it into the API extension would make it easier to manage. Would you be able to help with migrating? 

I've just made some minor changes to fallback when the scope is missing on the model and I left the $pageSize so you can introduce the changes you mentioned.

**Comment by ryanmitchell** [comment]
Thanks for the changes - thats a good approach.
Yeah I'll do the migration work, no problem at all. Brace yourself for more PR's!

**Comment by sampoyigi** [comment]
Bracing... 😄 I'll merge this.

**Comment by ryanmitchell** [comment]
Sorry, went to open a PR for moving the ext-local files over to this but couldn't until this one is merged. I'll open one once they are.

**Pull request merged**
