### PR TITLE
Bug fix in rest*() models

### LINKED ISSUE #15: BUG Create orders isn't working with menu_items
I tried to create an order via the API but it looks like the order_menus isn't created.

Here is an example of data:
```
{
    "status_id": 4,
    "order_type": "delivery",
    "payment": "cod",
    "menu_items": [
        {
            "name": "Napoli",
            "price": 10,
            "quantity": 1
        },
        {
            "name": "Bolognese",
            "price": 10,
            "quantity": 2
        }
    ]
}
```

Firstly, sending `menu_items` in the request body is causing an error.

now even without the `menu_items`, it looks like the `restAfterSave` from Order.php isn't called but instead from the RestController.php itself. And this method is empty in the RestController

It looks like a bug

### PR DESCRIPTION
**Pull request by ryanmitchell**
Apply to $this->controller, not $this
Should fix #15

### CODE REVIEW

**Comment by sampoyigi** [comment]
I've reverted 3db027c. With the proposed improvements, we will be able to extend/filter the request data in a separate class.

**Comment by sampoyigi** [comment]
I'll merge once you confirm you're okay with the changes.

**Comment by ryanmitchell** [comment]
Yep I'm happy as long as we/I remember to handle it in the bigger batch of changes.

**Comment by sampoyigi** [comment]
I don't think we'll miss it but I've taken note of it :)

**Pull request merged**
