### PR TITLE
Fractal, JSON:API and request validation

### PR DESCRIPTION
**Pull request by sampoyigi**
This PR integrates DingoAPI, they have put together a pretty neat package, a lot of great stuff to build secure APIs (fractal, JSON:API and request validation)

What’s changed:

* Back to using Fractal transformers for better response handling
* New Auth Manager
* `model`, `transformer` fields are no longer used, `model` as been replaced with a new repository layer for overloading models properties
* Now using Dingo custom auth provider to handle authentication 
* Removed `/admin/token` endpoint, just one endpoint will do for creating tokens with a check if a username or email was provided
* Renamed `issue:token` command to `api:token` so its grouped with other api commands
* Still work in progress on the Repository and FormRequest bits.

What do you think about making JSON:API the default response data structure?

### CODE REVIEW

**Comment by ryanmitchell** [comment]
After a bit of composer juggling I got Dingo to install :)

This all seems good - you've done most of it already! 👍 From my quick tests it seems to be feature compatible to the current version with the exception of the menus includes (which you've commented out so I guess you already know this).

JSON:Api should be the default response if we want to go forward in the right way... you seem to have done that?

Some thoughts:
- With switching to Dingo for token generation - will tokens already generated still work?
- With requests/rules can we merge that with rules in the admin portal to avoid duplication?

What do you need me to do?

**Comment by sampoyigi** [comment]
Great, happy its compatible with the current version 😌  Do you want to have a go at making the menus includes work?

JSON:API is already the default 😉 and nothing changed with issuing tokens.

That's what I thought, but yet to figure how best to handle a scenario where rules to validate the API request differs also how to handle the request query string validation.

**Comment by ryanmitchell** [comment]
Yep I can work on the menu includes - when I looked it I wondered whether including menu_options should automatically include menu_option_values?

**Comment by sampoyigi** [comment]
Yea makes sense for menu_options to include menu_option_values by default

**Comment by ryanmitchell** [comment]
Ok, i've checked the fractal docs and added it as a defaultInclude, however it doesnt nest like menu_options does which is a bit confusing... any idea why it gets added to "included" but menu_options doesn't? Feels like both should work the same way as they are both included?

**Comment by sampoyigi** [comment]
Now using the core FormRequests classes (left Order and Reservation form requests since their rules will always differ from the core)

> Ok, i've checked the fractal docs and added it as a defaultInclude, however it doesnt nest like menu_options does which is a bit confusing... any idea why it just gets added to "included" and not nested? Feels like both should work the same way as they are both included?

Were you able to sort this out?

**Comment by ryanmitchell** [comment]
Looks good!
No I wasn’t able to figure it - you any ideas?

**Comment by sampoyigi** [comment]
Erm, can't think of any but I'll debug later.

Just noticed an error from the form requests changes i just pushed... The validate when resolved doesn't look like the best approach.

**Comment by sampoyigi** [comment]
In case you missed it. Fixed the nested includes issue and form validation are complete...

**Comment by ryanmitchell** [comment]
Yeah it all looks good to me.

The only thing i’ve noticed is that renderSetupPartial() in the rsources model wont handle docs for endpoints added by other extensions. How can we accommodate that?

**Comment by ryanmitchell** [comment]
Another thought - should we also have an API allow action of "none" - ie its not available?

**Comment by sampoyigi** [comment]
For the `none` action, they can simply disable the action or use the `all` option.

Fixed the `renderSetupPartial ` issue

Can you help with updating response structure to JSON:API in the docs.

**Comment by ryanmitchell** [comment]
Docs are thats working well now, thanks.

Is there a way of a dev marking an endpoint as inactive in the registerApiResources() function? 

Yep I can work through all the responses in the docs - you just mean moving them to the attributes{} format? Do we need to document pagination?

**Comment by sampoyigi** [comment]
> Is there a way of a dev marking an endpoint as inactive in the registerApiResources() function?

Maybe an empty `actions` array?

> you just mean moving them to the attributes{} format? Do we need to document pagination?

Yup, the `attributes` format and pagination.

**Comment by sampoyigi** [comment]
Erm, can you add the rules for orders and reservations endpoints?

**Comment by ryanmitchell** [comment]
Working on the docs and getting an error when POST-ing:

```
{
    "message": "Missing controller in: Admin\\Requests\\Category",
    "status_code": 500,
    "debug": {
        "line": 42,
        "file": "/var/www/beta/site/app/system/classes/FormRequest.php",
        "class": "Igniter\\Flame\\Exception\\SystemException",
        "trace": [
            "#0 /var/www/beta/site/app/system/classes/FormRequest.php(103): System\\Classes\\FormRequest->getController()",
            "#1 /var/www/beta/site/app/system/classes/FormRequest.php(154): System\\Classes\\FormRequest->getForm()",
            "#2 /var/www/beta/site/app/system/classes/FormRequest.php(126): System\\Classes\\FormRequest->validationData()",
            "#3 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php(84): System\\Classes\\FormRequest->createDefaultValidator()",
            "#4 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(23): Illuminate\\Foundation\\Http\\FormRequest->getValidatorInstance()",
            "#5 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()",
            "#6 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(1102): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}()",
            "#7 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Container\\Container->fireCallbackArray()",
            "#8 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(1051): Illuminate\\Container\\Container->fireAfterResolvingCallbacks()",
            "#9 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(701): Illuminate\\Container\\Container->fireResolvingCallbacks()",
            "#10 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()",
            "#11 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()",
            "#12 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()",
            "#13 /var/www/beta/site/extensions/igniter/api/actions/RestController.php(182): Illuminate\\Foundation\\Application->make()",
            "#14 /var/www/beta/site/extensions/igniter/api/actions/RestController.php(81): Igniter\\Api\\Actions\\RestController->validateRequest()",
            "#15 [internal function]: Igniter\\Api\\Actions\\RestController->store()",
            "#16 /var/www/beta/site/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(428): call_user_func_array()",
            "#17 /var/www/beta/site/vendor/tastyigniter/flame/src/Support/Extendable.php(42): Igniter\\Flame\\Support\\Extendable->extendableCall()",
            "#18 [internal function]: Igniter\\Flame\\Support\\Extendable->__call()",
            "#19 /var/www/beta/site/extensions/igniter/api/classes/ApiController.php(43): call_user_func_array()",
            "#20 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Igniter\\Api\\Classes\\ApiController->callAction()",
            "#21 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()",
            "#22 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()",
            "#23 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()",
            "#24 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()",
            "#25 /var/www/beta/site/vendor/dingo/api/src/Http/Middleware/Auth.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#26 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Auth->handle()",
            "#27 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#28 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()",
            "#29 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#30 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()",
            "#31 /var/www/beta/site/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#32 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\PrepareController->handle()",
            "#33 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#34 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()",
            "#35 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()",
            "#36 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()",
            "#37 /var/www/beta/site/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\\Routing\\Router->dispatchToRoute()",
            "#38 /var/www/beta/site/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): October\\Rain\\Router\\CoreRouter->dispatch()",
            "#39 /var/www/beta/site/vendor/dingo/api/src/Routing/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch()",
            "#40 /var/www/beta/site/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch()",
            "#41 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}()",
            "#42 /var/www/beta/site/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#43 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\\Flame\\Setting\\Middleware\\SaveSetting->handle()",
            "#44 /var/www/beta/site/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#45 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()",
            "#46 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#47 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
            "#48 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#49 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
            "#50 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#51 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()",
            "#52 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#53 /var/www/beta/site/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then()",
            "#54 /var/www/beta/site/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter()",
            "#55 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Request->handle()",
            "#56 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#57 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()",
            "#58 /var/www/beta/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
            "#59 /var/www/beta/site/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()",
            "#60 {main}"
        ]
    }
}
```

**Comment by ryanmitchell** [comment]
Ok opened a PR for docs and also for rules.
If you get a chance to do the order/reservation docs that would be great - its pretty time consuming so it may be a couple of days before I get to it.

**Comment by sampoyigi** [comment]
Thank you for the docs!!

**Comment by ryanmitchell** [comment]
Working on the last one now

**Comment by sampoyigi** [comment]
@BreakSecurity any chance you can help us with testing here?

**Comment by sampoyigi** [comment]
Lost track of this one. I think we've got everything covered here?

**Comment by ryanmitchell** [comment]
Yep. You had asked breaksecurity to test?

**Comment by sampoyigi** [comment]
Yea I reminded him on slack.. How about your side? Is it still compatible with the current version and can you help check for breaking changes, if any?

**Comment by ryanmitchell** [comment]
It’s all good from a GET perspective. I don’t do any pushing or updating in our apps so haven’t tested that yet. 

Will be testing that throughly when I move onto the back office app :)

I would say it’s definitely feature compatible at this point - nothing to stop a release.

**Comment by sampoyigi** [comment]
Great stuff! I'll wait for breaksecurity to complete the tests.

**Pull request merged**
