### PR TITLE
Add menu_items and options to api

### PR DESCRIPTION
**Pull request by LonnyX**
still a lot to do but it's first first draft

### CODE REVIEW

**Comment by sampoyigi** [comment]
I and Ryan are discussing some improvements to the validation and controller layer so I'll come back to this once we have that sorted. Anyways, Thank you for the PR!

**Comment by sampoyigi** [comment]
@LonnyX Thanks for your patience! Can you work on merging this into the `integrate-dingo-api` branch? Feel free to open another PR if necessary.

**Comment by ryanmitchell** [comment]
This should be covered off already by the work we have done on the dingo branch.
I think we should close it.
Thanks for the contribution @LonnyX - really appreciate it.

**Comment by sampoyigi** [comment]
Cool stuff... 

Thank you @LonnyX

**Pull request closed without merging**
