### PR TITLE
Add select * to ensure we get all location data even if lat/lon passed

### PR DESCRIPTION
**Pull request by ryanmitchell**
Part of: https://github.com/tastyigniter/TastyIgniter/pull/582
And as mentioned here: https://github.com/tastyigniter/TastyIgniter/issues/557

### CODE REVIEW

**Comment by sampoyigi** [comment]
I've merged the core PR and will merge this PR after we're done with #23 ;)

**Comment by sampoyigi** [comment]
Do I still need to merge this?

**Comment by ryanmitchell** [comment]
Its still needed due to the lat/long issue

**Comment by sampoyigi** [comment]
Merged, Github seems to be moving slow!

**Pull request merged**
