### PR TITLE
API additions

### PR DESCRIPTION
**Pull request by ryanmitchell**
1. Adding menu_options and categories to menus end point
2. Allow selection of verbs in settings

### CODE REVIEW

**Comment by sampoyigi** [comment]
For the verbs would it be possible to use the meta database column instead of creating a new one?

**Comment by ryanmitchell** [comment]
Yes could do.

If I do that using field of meta[verbs], then how do I do the equivalent getVerbsOptions() as its now an array and throwing an error? I cant see any equivalent code in any of the other models.

**Comment by ryanmitchell** [comment]
Ok this should be it now - brought verbs into meta, and also added all the other end points that I *think* people might need from core.

**Comment by sampoyigi** [comment]
Let me know what you think of the changes before I merge them 😄

**Comment by ryanmitchell** [comment]
Updated to use language pack rather than hard coded strings.

Note: I've changed the comment under allowed actions to reflect the functionality (selecting none turns off the api end point - which is what it should do in my opinion, otherwise there is no way of turning it off!).

**Comment by sampoyigi** [comment]
Fine with the language pack and actions.

**Pull request merged**
